# Generated by Django 4.0.2 on 2022-02-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sabt',
            old_name='inconme',
            new_name='income',
        ),
    ]
