# Generated by Django 4.0.2 on 2022-02-13 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_inconme_sabt_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 11, 24, 39, 418755, tzinfo=utc)),
        ),
    ]
